import { HttpStatus } from "../typings/";

export const HTTP_STATUS: HttpStatus = {
  CONTINUE: { code: 100, message: "continue" },
  SWITCHING_PROTOCOLS: { code: 101, message: "switching_protocols" },
  PROCESSING: { code: 102, message: "processing" },
  EARLY_HINTS: { code: 103, message: "early_hints" },
  OK: { code: 200, message: "ok" },
  CREATED: { code: 201, message: "created" },
  ACCEPTED: { code: 202, message: "accepted" },
  NON_AUTHORITATIVE_INFORMATION: {
    code: 203,
    message: "non_authoritative_information",
  },
  NO_CONTENT: { code: 204, message: "no_content" },
  RESET_CONTENT: { code: 205, message: "reset_content" },
  PARTIAL_CONTENT: { code: 206, message: "partial_content" },
  MULTI_STATUS: { code: 207, message: "multi_status" },
  MULTIPLE_CHOICES: { code: 300, message: "multiple_choices" },
  MOVED_PERMANENTLY: { code: 301, message: "moved_permanently" },
  MOVED_TEMPORARILY: { code: 302, message: "moved_temporarily" },
  SEE_OTHER: { code: 303, message: "see_other" },
  NOT_MODIFIED: { code: 304, message: "not_modified" },
  USE_PROXY: { code: 305, message: "use_proxy" },
  TEMPORARY_REDIRECT: { code: 307, message: "temporary_redirect" },
  PERMANENT_REDIRECT: { code: 308, message: "permanent_redirect" },
  BAD_REQUEST: { code: 400, message: "bad_request" },
  UNAUTHORIZED: { code: 401, message: "unauthorized" },
  PAYMENT_REQUIRED: { code: 402, message: "payment_required" },
  FORBIDDEN: { code: 403, message: "forbidden" },
  NOT_FOUND: { code: 404, message: "not_found" },
  METHOD_NOT_ALLOWED: { code: 405, message: "method_not_allowed" },
  NOT_ACCEPTABLE: { code: 406, message: "not_acceptable" },
  PROXY_AUTHENTICATION_REQUIRED: {
    code: 407,
    message: "proxy_authentication_required",
  },
  REQUEST_TIMEOUT: { code: 408, message: "request_timeout" },
  CONFLICT: { code: 409, message: "conflict" },
  GONE: { code: 410, message: "gone" },
  LENGTH_REQUIRED: { code: 411, message: "length_required" },
  PRECONDITION_FAILED: { code: 412, message: "precondition_failed" },
  REQUEST_TOO_LONG: { code: 413, message: "request_too_long" },
  REQUEST_URI_TOO_LONG: { code: 414, message: "request_uri_too_long" },
  UNSUPPORTED_MEDIA_TYPE: { code: 415, message: "unsupported_media_type" },
  REQUESTED_RANGE_NOT_SATISFIABLE: {
    code: 416,
    message: "requested_range_not_satisfiable",
  },
  EXPECTATION_FAILED: { code: 417, message: "expectation_failed" },
  IM_A_TEAPOT: { code: 418, message: "im_a_teapot" },
  INSUFFICIENT_SPACE_ON_RESOURCE: {
    code: 419,
    message: "insufficient_space_on_resource",
  },
  METHOD_FAILURE: { code: 420, message: "method_failure" },
  MISDIRECTED_REQUEST: { code: 421, message: "misdirected_request" },
  UNPROCESSABLE_ENTITY: { code: 422, message: "unprocessable_entity" },
  LOCKED: { code: 423, message: "locked" },
  FAILED_DEPENDENCY: { code: 424, message: "failed_dependency" },
  TOO_EARLY: { code: 425, message: "too_early" },
  UPGRADE_REQUIRED: { code: 426, message: "upgrade_required" },
  PRECONDITION_REQUIRED: { code: 428, message: "precondition_required" },
  TOO_MANY_REQUESTS: { code: 429, message: "too_many_requests" },
  REQUEST_HEADER_FIELDS_TOO_LARGE: {
    code: 431,
    message: "request_header_fields_too_large",
  },
  UNAVAILABLE_FOR_LEGAL_REASONS: {
    code: 451,
    message: "unavailable_for_legal_reasons",
  },
  INTERNAL_SERVER_ERROR: { code: 500, message: "internal_server_error" },
  NOT_IMPLEMENTED: { code: 501, message: "not_implemented" },
  BAD_GATEWAY: { code: 502, message: "bad_gateway" },
  SERVICE_UNAVAILABLE: { code: 503, message: "service_unavailable" },
  GATEWAY_TIMEOUT: { code: 504, message: "gateway_timeout" },
  HTTP_VERSION_NOT_SUPPORTED: {
    code: 505,
    message: "http_version_not_supported",
  },
  VARIANT_ALSO_NEGOTIATES: { code: 506, message: "variant_also_negotiates" },
  INSUFFICIENT_STORAGE: { code: 507, message: "insufficient_storage" },
  LOOP_DETECTED: { code: 508, message: "loop_detected" },
  NOT_EXTENDED: { code: 510, message: "not_extended" },
  NETWORK_AUTHENTICATION_REQUIRED: {
    code: 511,
    message: "network_authentication_required",
  },
};
